# SteamSpy:
Creating dataframe using steam spy API.

In [1]:
#imports
import requests
import pandas as pd
import json

In [2]:
# get API and keep the important columns. 

#build first dataframe
url = "https://steamspy.com/api.php?request=all"
res = requests.get(url)
data_json = res.json()
steam_spy_all = pd.DataFrame.from_dict(data_json, orient='index')
steam_spy_all.sort_values('positive', axis=0, ascending=False)

#concat other dataframes
for i in range(1,5):
    URL = url + "&page=" + "{0}".format(i)
    res = requests.get(URL)
    data_json = res.json()
    new_pd = pd.DataFrame.from_dict(data_json, orient='index')
    steam_spy_all = pd.concat([steam_spy_all, new_pd], axis = 0)
    
#drop unnecessary columns
steam_spy_all.drop(columns=['ccu', 'discount', 'initialprice', 'median_2weeks', 'average_2weeks', 'userscore', 'score_rank', 'appid'], inplace=True)

#sort by most positive at the top
steam_spy_all = steam_spy_all.sort_values('positive', axis=0, ascending=False)
steam_spy_all

,name,developer,publisher,positive,negative,owners,average_forever,median_forever,price
730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,5382473,722938,"50,000,000 .. 100,000,000",30578,7329,0
570,Dota 2,Valve,Valve,1377514,267155,"100,000,000 .. 200,000,000",36994,1118,0
271590,Grand Theft Auto V,Rockstar North,Rockstar Games,1064898,202052,"20,000,000 .. 50,000,000",13027,5973,1480
578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",1037820,844274,"20,000,000 .. 50,000,000",26778,11760,2999
359550,Tom Clancy's Rainbow Six Siege,Ubisoft Montreal,Ubisoft,884943,128398,"20,000,000 .. 50,000,000",13964,2646,799
...,...,...,...,...,...,...,...,...,...
588140,ESCAPE FROM VOYNA: Dead Forest,Dead Turtle,Dead Turtle,0,1,"500,000 .. 1,000,000",0,0,467
8640,RACE On,SimBin,SimBin,0,0,"100,000 .. 200,000",1,1,399
21110,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",219,268,824
21120,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",254,321,824
905270,Merlin Soccer,Educational Games,Educational Games,0,1,"200,000 .. 500,000",0,0,49

In [3]:
#droping dups'
steam_spy_all.drop_duplicates(keep='first', inplace=True)
steam_spy_all

,name,developer,publisher,positive,negative,owners,average_forever,median_forever,price
730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,5382473,722938,"50,000,000 .. 100,000,000",30578,7329,0
570,Dota 2,Valve,Valve,1377514,267155,"100,000,000 .. 200,000,000",36994,1118,0
271590,Grand Theft Auto V,Rockstar North,Rockstar Games,1064898,202052,"20,000,000 .. 50,000,000",13027,5973,1480
578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",1037820,844274,"20,000,000 .. 50,000,000",26778,11760,2999
359550,Tom Clancy's Rainbow Six Siege,Ubisoft Montreal,Ubisoft,884943,128398,"20,000,000 .. 50,000,000",13964,2646,799
...,...,...,...,...,...,...,...,...,...
588140,ESCAPE FROM VOYNA: Dead Forest,Dead Turtle,Dead Turtle,0,1,"500,000 .. 1,000,000",0,0,467
8640,RACE On,SimBin,SimBin,0,0,"100,000 .. 200,000",1,1,399
21110,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",219,268,824
21120,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",254,321,824
905270,Merlin Soccer,Educational Games,Educational Games,0,1,"200,000 .. 500,000",0,0,49

In [4]:
#removing spacial editions games
steam_spy_all = steam_spy_all[steam_spy_all["name"].str.contains("Edition")==False]
steam_spy_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4804 entries, 730 to 905270
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             4804 non-null   object
 1   developer        4804 non-null   object
 2   publisher        4804 non-null   object
 3   positive         4804 non-null   int64
 4   negative         4804 non-null   int64
 5   owners           4804 non-null   object
 6   average_forever  4804 non-null   int64
 7   median_forever   4804 non-null   int64
 8   price            4804 non-null   object
dtypes: int64(4), object(5)
memory usage: 375.3+ KB

In [5]:
steam_spy_all.to_csv("steam_spy_clean.csv")

In [3]:
steam_spy_clean = pd.read_csv("steam_spy_clean.csv")
steam_spy_clean

,Unnamed: 0,name,developer,publisher,positive,negative,owners,average_forever,median_forever,price
0,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,5382473,722938,"50,000,000 .. 100,000,000",30578,7329,0
1,570,Dota 2,Valve,Valve,1377514,267155,"100,000,000 .. 200,000,000",36994,1118,0
2,271590,Grand Theft Auto V,Rockstar North,Rockstar Games,1064898,202052,"20,000,000 .. 50,000,000",13027,5973,1480
3,578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",1037820,844274,"20,000,000 .. 50,000,000",26778,11760,2999
4,359550,Tom Clancy's Rainbow Six Siege,Ubisoft Montreal,Ubisoft,884943,128398,"20,000,000 .. 50,000,000",13964,2646,799
...,...,...,...,...,...,...,...,...,...,...
4799,588140,ESCAPE FROM VOYNA: Dead Forest,Dead Turtle,Dead Turtle,0,1,"500,000 .. 1,000,000",0,0,467
4800,8640,RACE On,SimBin,SimBin,0,0,"100,000 .. 200,000",1,1,399
4801,21110,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",219,268,824
4802,21120,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",254,321,824
4803,905270,Merlin Soccer,Educational Games,Educational Games,0,1,"200,000 .. 500,000",0,0,49

In [5]:
steam_spy_clean.drop(columns=["Unnamed: 0"], inplace=True)
steam_spy_clean.reset_index(drop=True)
steam_spy_clean

,name,developer,publisher,positive,negative,owners,average_forever,median_forever,price
0,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,5382473,722938,"50,000,000 .. 100,000,000",30578,7329,0
1,Dota 2,Valve,Valve,1377514,267155,"100,000,000 .. 200,000,000",36994,1118,0
2,Grand Theft Auto V,Rockstar North,Rockstar Games,1064898,202052,"20,000,000 .. 50,000,000",13027,5973,1480
3,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",1037820,844274,"20,000,000 .. 50,000,000",26778,11760,2999
4,Tom Clancy's Rainbow Six Siege,Ubisoft Montreal,Ubisoft,884943,128398,"20,000,000 .. 50,000,000",13964,2646,799
...,...,...,...,...,...,...,...,...,...
4799,ESCAPE FROM VOYNA: Dead Forest,Dead Turtle,Dead Turtle,0,1,"500,000 .. 1,000,000",0,0,467
4800,RACE On,SimBin,SimBin,0,0,"100,000 .. 200,000",1,1,399
4801,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",219,268,824
4802,F.E.A.R.,"Monolith Productions, Inc., Timegate","Warner Bros. Games, Warner Bros. Interactive E...",0,0,"1,000,000 .. 2,000,000",254,321,824
4803,Merlin Soccer,Educational Games,Educational Games,0,1,"200,000 .. 500,000",0,0,49

In [6]:
steam_spy_clean.to_csv("steam_spy_clean.csv")